Old apple clone
Naqhid/AppleClone_project pull request #3
Opened 2020-09-29 14:46 UTC by Davidosky007

> #The Old Apple Website Clone
> 
> In this project we:
> 
> *we made use of background images
*we made use of Gradients
*added a favicon for the page title

2020-09-29 15:20 UTC, jubaan requested changes
# This Pull Request follows observations made in PR #2. 

### NOTES: Please use always the same PR that you submit initially. It keeps track of history and reflects the observations and decisions made through the elaboration of the project.

# Status: Changes Required :recycle:

## :clap: :clap: Great work team!, you have solved some of all the previous required changes!

Still, there are some issues to be addressed. Kindly work on them before submitting them for a re-review.

## Required Changes
### [Mandatory]

- [ ] Website still is not displaying correctly
- [ ] Navbar links are difficult to perceive, we should increase the ```font-weight```.
![image](https://user-images.githubusercontent.com/25774518/94577457-3d9e2600-023c-11eb-8738-789b1ce7f7d1.png)

- [ ]  Navbar should be inside the `<header>` tag. We should move it outside the `<main>` tag. See inline comments.

- [ ]  All images should have an alternate text. We should fill the `alt=" "` attribute, never leave it blank. I've seen you have fill it up with ```img``` text. We should improve and make a meaningful and descriptive alternative text.
**Actual**: ```alt="img"```
**Improved** :+1: : ```alt="Iphone 5S"```

### [OPTIONAL] 
- [ ]  The project should follow this structure:
 ```
/
   css/
     style.css
   img/
     ... some images...
   js/
     ... some js scripts...
   index.html
 ```
## [Previous Required Changes PR #2] -----------------------
> # Status: Changes Required 
> ##   Hello Team!! Great effort on the project!!
>  Great that you use media queries even if they were not required.
> 
> ## Required Changes
> ### [Mandatory] 
> * [x]  MIT license link takes to a Linkedin profile. It should take to the actual license.
- [ ]  Website is not displaying properly
>   ![image](https://user-images.githubusercontent.com/25774518/94557301-002d9e80-0224-11eb-96bd-0f3b271616c8.png)
- [ ]  Navbar link elements are not visible enough.
>   ![image](https://user-images.githubusercontent.com/25774518/94557380-19cee600-0224-11eb-930e-98b68cf9d716.png)
- [ ]  Navbar should be inside the `<header>` tag. We should move it outside the `<main>` tag.
> * [x]  Footer should be outside the `<main>` tag.
- [ ]  All images should have an alternate text. We should fill the `alt=" "` attribute, never leave it blank.
> 
> ### [OPTIONAL] 
> * [ ]  The project should follow this structure:
> 
> ```
> /
>   css/
>     style.css
>   img/
>     ... some images...
>   js/
>     ... some js scripts...
>   index.html
> ```
> 
> ### [Comments] 
> * [ ]  After the changes have been made do nor forget to update the live preview link in the README
> 
## =====================================

## Keep up the great work  and Happy Coding  !!

2020-09-29 15:24 UTC, jubaan requested changes

2020-09-29 15:24 UTC, jubaan commented on index.html
> +        </nav>
- [ ] Navbar should be wrapped around ```<header>``` HTML tag, and outside the ```<main>``` container. Example:
```
...
  <header>
    <nav>
      ... nav elements ...
    </nav>
  </header>

  <main>
    ... main content ...
  </main>
...
```

2020-09-29 15:24 UTC, jubaan commented on index.html
> +      </div>
- [ ] Give ```alt``` attribute descriptive alternative text as in the example given.

2020-09-30 04:27 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## Great job workking on the required changes! 
## Congratulations :clap: :clap: :clap:

## See you at the top :rocket: !!!

2020-09-30 04:29 UTC, Davidosky007 commented
Thanks

On Wed, 30 Sep 2020, 5:27 am Julio Añoveros, <notifications@github.com>
wrote:

> *@jubaan* approved this pull request.
> Status: Approved 🎉 🎉 🎉 Great job workking on the required changes! Congratulations
> 👏 👏 👏 See you at the top 🚀 !!!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Naqhid/AppleClone_project/pull/3#pullrequestreview-499075829>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQQWXWKHYV3AAE433V6TZ3SIKXTXANCNFSM4R54YU4A>
> .
>

2020-09-30 06:57 UTC, merged